### ISSUE TITLE
Remove this repository.

### ISSUE THREAD

**Issue by minisbett** [Airkek/ultimate-osu-server-launcher#4]
Please remove this repository or leave a copyright notice (e.g. by forking mine) as defined per GPL-3.0 license. If you do not follow this within 7 days after this message, I will be contacting GitHub for further actions.

Other than that; Do not use server switchers, they are unsafe and outdated. Please consider using the -devserver client flag instead.

**Comment by minisbett** [comment]
nevermind, I saw that you had forked my repo too but this seems to be a clone of my server switcher, all good.

**Comment by Airkek** [comment]
Just fyi, it's -devserver switcher that have nothing common with your projects.
Sorry for my answer in #1
